### ISSUE TITLE
pointpillars_multihead.yaml 问题

### ISSUE THREAD

**Issue by zhutongseu1994** [Qiuzhongyuan/pointpillars_pytorch_trt#8]
root@9d0d5c916bcc:~/share/pytorch/tools# python train.py --cfg_file=/root/share/pytorch/tools/cfgs/kitti_models/pointpillar_multihead.yaml 

/root/share/pytorch/tools/cfgs/kitti_models/pointpillar_multihead.yaml
/root/share/pytorch/pcdet/config.py:76: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  new_config = yaml.load(f)
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    main()
  File "train.py", line 59, in main
    args, cfg = parse_config()
  File "train.py", line 48, in parse_config
    cfg_from_yaml_file(args.cfg_file, cfg)
  File "/root/share/pytorch/pcdet/config.py", line 77, in cfg_from_yaml_file
    merge_new_config(config=config, new_config=new_config)
  File "/root/share/pytorch/pcdet/config.py", line 52, in merge_new_config
    if '_BASE_CONFIG_' in new_config:
TypeError: argument of type 'NoneType' is not iterable

请问用您代码中提供的pointpillars_multihead.yaml训练 出现这样的错误如何解决？

**Comment by Qiuzhongyuan** [comment]
没有遇到过这样的问题。。

**Comment by zhutongseu1994** [comment]
> 没有遇到过这样的问题。。

用提供的docker也是报出这样的问题....
